//go:build wasm
// +build wasm

package logger

// This file is auto-generated by build.sh
// DO NOT EDIT MANUALLY

func initConfig() {
	currentLevel = LevelTrace
	categories = map[string]bool{
		"MEMO": true,
		"COMPUTED": true,
	}
}
